### ISSUE TITLE
(Mssqlex.Error) odbc_not_started

### ISSUE THREAD

**Issue by Olshansk** [findmypast-oss/mssql_ecto#14]
I'm getting the following error when I start up my application: `Mssqlex.Protocol (#PID<0.19212.0>) failed to connect: ** (Mssqlex.Error) odbc_not_started`.

I followed the instructions https://github.com/findmypast-oss/mssqlex to install erlang-odbc and Microsoft’s ODBC Driver for SQL Server.

I’m working from within a Docker containing running Debian 8.

Ecto version 2.1
Elixir version 1.3.4

I can confirm that i can telenet to the mssql server and have used a node cli client to query it.

Any ideas?

**Comment by shdblowers** [comment]
@Olshansk shall we close this issue?

You said on slack you got it working once you upgraded to Elixir 1.4

**Comment by Olshansk** [comment]
@shdblowers Yup, that was the issue. The lesson learnt is to always read the README :)

**Comment by Olshansk** [comment]
@shdblowers The README actually contains this piece of text

> If you are running an Elixir version below 1.4 or you have the applications key set in your application options, you will also need to update your list of running application

Unless it's been tested with version < 1.4, I think it's worth removing so as not to mislead people. I personally could not get it working with elixir 1.3.X, but it's possible that I had other conflicts which was causing problems.

**Comment by shdblowers** [comment]
I agree with what you've said @Olshansk.

Will make the change.

**Comment by shdblowers** [comment]
Done in this commit: https://github.com/findmypast-oss/mssql_ecto/commit/a2f613c4d15d082de3054822e5fb3be287169959

**Comment by shdblowers** [comment]
I have also called out in the mix file we don't support below Elixir 1.4.0 https://github.com/findmypast-oss/mssql_ecto/commit/e59c07c4ed3890dd75adbc09929d3e510d91ff45

**Comment by Olshansk** [comment]
Thanks for updating it :)

**Comment by katbow** [comment]
I have Elixir 1.4.0 and am still getting this error. 

```
[error] Mssqlex.Protocol (#PID<0.3246.0>) failed to connect: ** (Mssqlex.Error) odbc_not_started
```

I tried adding it in to applications as specified previously in the README to be sure, then had a different error. 

``` 
[error] Mssqlex.Protocol (#PID<0.723.0>) failed to connect: ** (Mssqlex.Error) [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found Connection to database failed. | ODBC_CODE 01000 | SQL_SERVER_CODE 0
```

**Comment by shdblowers** [comment]
@katbow can you open up a new issue and fill in as much information as you can on that?

The reason why is these two issues could be completely unrelated and I need more information to investigate further.

**Comment by katbow** [comment]
Thanks @shdblowers. New issue here -> #15
